# Lobby, Prison, Cell, Adventure, Home
Server: Prison

# LuckPerms Context for auto-assigning permissions with correct Context
# Lobby, Prison, Adventure
Context: Prison

# Should arrows be despawned after hitting an enemy, rather than remaining on the ground
Arrow-Despawn: true
