name: AdventuresCraft
version: 1.0
api-version: 1.16
main: monzter.adventurescraft.plugin.AdventuresCraft
depend: [MMOItems, PlaceholderAPI, HolographicDisplays, WorldGuard, Votifier, MythicMobs, helper, BetonQuest, LuckPerms, MysqlPlayerDataBridge]
commands:
  MiningPass:
  Booster:
    permission: '*'
  Sell:
  Discord:
  Pet:
  Bank:
    aliases: [Enderchest, Economy]
  Warp:
    aliases: [Travel]
  Mine:
  Spawn:
    aliases: [Yard]
  Quest:
    aliases: [Quests, QuestMenu, QuestsMenu]
  ActiveQuest:
    aliases: [ActiveQuests, CurrentQuest, CurrentQuests]
  UnclaimedQuest:
    aliases: [UnclaimedQuests]
  Login:
  PointsAdd:
    permission: '*'
    usage: "/PointsAdd [Amount] [Material]"
  PointsAmount:
    permission: '*'
    usage: "/PointsAmount [Material]"
  Stat:
    permission: '*'
    usage: "/Stat [Stat] [Player]"
  RestartTime:
    permission: '*'
  Vote:
  Reward:
    permission: '*'
    usage: "/Reward [Stat] [Amount] [Player]"
  PetUnequip:
    usage: "/PetUnequip [pet-name]"
  DropTables:
    permission: '*'
    permission-message: You do not have permission to use this command.
    usage: "/DropTables [table-name]"
  Hatch:
    usage: "/Hatch [egg-rarity]"
  EnchantReward:
