name: AdventuresCraft
version: 1.0
api-version: 1.16
main: monzter.adventurescraft.plugin.AdventuresCraft
depend: [MMOItems, PlaceholderAPI, HolographicDisplays, WorldGuard, Votifier]
commands:
  Captcha:
    description: 'Unlock chat!'
    usage: '/<command> <code>'
  BattlePass:
  Booster:
  Sell:
  Discord:
  Pet:
  Bank:
    aliases: [Enderchest, Vault]
  Warp:
    aliases: [Travel]
  Mine:
  Spawn:
    aliases: [Yard]
  Quest:
    aliases: [Quests, QuestMenu, QuestsMenu]
  ActiveQuest:
    aliases: [ActiveQuests, CurrentQuest, CurrentQuests]
  UnclaimedQuest:
    aliases: [UnclaimedQuests]
  Login:
  PointsDebug:
  Stat:
  RestartTime:
  Vote: